#!/usr/bin/env ruby

require './lib/util.rb'
require 'optparse'

options = {}

OptionParser.new do |opts|
  opts.banner = 'Clones each repo specified in repos.txt.'
  opts.banner += "\n\n"
  opts.banner = 'Usage: ./scripts/checkout'
end.parse!

repos = check_repos_txt(check_exist: false)

repos.each_with_index do |repo, i|
  dir = "repos/#{repo}"
  if !Dir.exist? dir
    puts "#{repo}:"
    result = system "git clone git@github.com:#{repo}.git #{dir}"
    unless result
      STDERR.puts "ERROR: Failed to clone: git@github.com:#{repo}.git"
      exit 1
    end
    puts if i < repos.length - 1
  else
    puts "#{repo}: Already exists."
    puts if i < repos.length - 1
  end
end
