#!/usr/bin/env ruby

require 'cgi'

unless File.exists? 'repos.txt'
  STDERR.puts 'ERROR: File not found: repos.txt'
  STDERR.puts ''
  STDERR.puts 'repos.txt should contain a list of Git repo paths like:'
  STDERR.puts '  nicholasdower/foo'
  STDERR.puts '  nicholasdower/bar'
  exit 1
end

repos = File.readlines('repos.txt').map(&:strip)

repos.each do |repo|
  dir = "repos/#{repo.strip}"
  unless Dir.exists? dir
    STDERR.puts "ERROR: Directory does not exist: #{dir}"
    exit 1
  end
end


query = "is:open is:pr " + repos.map { |r| "repo:#{r.strip}" }.join(' ')
url = "https://github.com/pulls?q=#{CGI.escape(query)}"

`open #{url}`
