#!/usr/bin/env ruby

require './lib/util.rb'
require 'cgi'

repos = check_repos_txt(check_exist: false)

query = "is:open is:pr " + repos.map { |r| "repo:#{r.strip}" }.join(' ')
url = "https://github.com/pulls?q=#{CGI.escape(query)}"

`open #{url}`
