#!/usr/bin/env ruby

require 'optparse'

options = {}

parser = OptionParser.new do |opts|
  opts.banner = 'Executes the specified command on each repo.'
  opts.banner += "\n\n"
  opts.banner += 'Usage: ./scripts/execute [-s] <command>'

  opts.on('-s', '--silent', 'Don\'t print repo paths before executing command.') do |s|
    options[:silent] = s
  end
end

parser.parse!

silent = options[:silent]

if ARGV.length == 0 then
  STDERR.puts 'ERROR: You must specify something to execute.'
  STDERR.puts
  STDERR.puts parser.help
  exit 1
end

unless File.exists? 'repos.txt'
  STDERR.puts 'ERROR: File not found: repos.txt'
  STDERR.puts ''
  STDERR.puts 'repos.txt should contain a list of Git repo paths like:'
  STDERR.puts '  nicholasdower/foo'
  STDERR.puts '  nicholasdower/bar'
  exit 1
end

repos = File.readlines('repos.txt').map(&:strip)

repos.each do |repo|
  dir = "repos/#{repo}"
  unless Dir.exists? dir
    STDERR.puts "ERROR: Directory does not exist: #{dir}"
    exit 1
  end
end

repos.each_with_index do |repo, i|
  dir = "repos/#{repo}"
  puts "#{repo}:" unless silent
  system ARGV.join(' ')
  puts unless silent || i == repos.length - 1
end
